### PR TITLE
HTML, CSS & Git Basics

### PR DESCRIPTION
**Pull request by olegStepura99**
1. Task:https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css-git

### CODE REVIEW

**Comment by olegStepura99** [comment]
init: start project

**Comment by olegStepura99** [comment]
add contact and peersonal information

**Comment by olegStepura99** [comment]
add skills and sample code

**Comment by olegStepura99** [comment]
add education and level of English

**Comment by lel9l** [comment]
**Your rating - 71 points**
Feedback on points of TK:
Not completed / not scored points:
1) content is placed in a block that is horizontally centered on the page
_**feedback: the page is not centered**_
Partially Completed Items:
1) the layout is valid. Check the validity of the layout: https://validator.w3.org/
**_feedback: https://validator.w3.org/
There are errors and warnings._**
2) semantic layout. 2 points for each unique semantic HTML5 tag

3) contacts for communication and a list of skills are designed as a list ul> li
**_feedback: Contacts for communication are not designed as a list_**
4) the requirements for the repository are met: there is a link to the task, a screenshot of the CV page, a link to the deployment of the CV page on GitHub Pages, the deadline date is indicated, self-assessment is completed

Completed items:
1) headers h1-h6 are used. 5 points for each unique title

2) CSS styles are used to design CV

3) there is an image on the CV page, the aspect ratio of the image is not distorted, the image has an alt attribute

4) CV contains contacts, brief information about yourself, skills, code examples, education, level of English

5) CV is done in English

**Pull request merged**
